package com.prathamngundikere.wasd.domain

enum class FireStoreError : Error{
    UNABLE_TO_INSERT_USER,
    UNABLE_TO_UPDATE_USER,
    USER_NOT_FOUND,
    UNABLE_TO_GET_USER,
    UNABLE_TO_INSERT_HABIT,
    UNABLE_TO_UPDATE_HABIT,
    HABIT_NOT_FOUND,
    UNABLE_TO_GET_HABIT,
    UNABLE_TO_INSERT_TASK,
    UNABLE_TO_UPDATE_TASK,
    UNABLE_TO_GET_TASK,
    TASK_NOT_FOUND,
    UNABLE_TO_INSERT_REWARD,
    UNABLE_TO_UPDATE_REWARD,
    UNABLE_TO_GET_REWARD,
    REWARD_NOT_FOUND
}